name: Final Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev zip unzip
          pip install --user --upgrade buildozer Cython==0.29.33 setuptools

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Чистим кэш и собираем заново
          buildozer android clean
          # Запускаем сборку
          yes | buildozer android debug
        
      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
